name: deploy to ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh로 ec2 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          # 여기서 저 변수들은 github의 해당 repository settings에서 Secrets and variables -> actions에서 각각 설정해준다.
          host: ${{ secrets.EC2_HOST }} # EC2의 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 접속 username
          key: ${{ secrets.EC2_PRIVATE_KEY }} # EC2의 Key 파일의 내부 텍스트
          script_stop: true # 아래 script 중 실패하는 명령이 하나라도 있으면 실패로 처리
          script: |
            cd /home/ubuntu/2024springboot
            git pull origin main
            cd /Ex12_Food
            ./gradlew bootwar
